### ISSUE TITLE
Email gets transformed in request

### ISSUE THREAD

**Issue by odnarb** [kickboxio/kickbox-node#7]
The API transforms the original requested email: caps, dots (periods) get removed for some domains.. I understand why as some domains don't care. However, this doesn't seem proper of kickbox's API to do such altering when it's unsolicited.

If the email is going to be transformed via kickbox, return a reference to the original/unaltered email address.

I cannot stress the importance of this enough.

Thanks

**Comment by danhstevens** [comment]
Thanks for reaching out. You're correct that the API does return a sanitized version of the email address (http://docs.kickbox.io/docs/using-the-api#the-response):

> email string - Returns a normalized version of the provided email address. (BoB@example.com ->bob@example.com)

The reasoning behind this is that you hold the original address when you make the request

```
// Pseudo-code incoming!
email = "BoB@example.com";
response = verify(email);

// Use email var for exact string comparisons, etc
// Use response.email for sanitized purposes (checking a database, etc)
```

With that, you get the best of both worlds. There's no need for Kickbox to return the email variable you passed since you already know it, and the normalized data is important for things like plus addresses, database queries, etc.

Hope that helps!
